#!/bin/bash

hour=$(date '+%H')
hour=$((10#$hour))
hour_mod=$((hour % 12))
[ "$hour_mod" -eq 0 ] && hour_mod=12

icons=(
  "󱑋"
  "󱑌"
  "󱑍"
  "󱑎"
  "󱑏"
  "󱑐"
  "󱑑"
  "󱑒"
  "󱑓"
  "󱑔"
  "󱑕"
  "󱑖"
)

icon=${icons[$((hour_mod - 1))]}
printf " %s %s \n" "$icon" "$(date '+%H:%M')"
