#!/bin/sh

hour=$(date '+%I')

case "$hour" in
"00" | "12") icon="󱑖" ;;
"01") icon="󱑋" ;;
"02") icon="󱑌" ;;
"03") icon="󱑍" ;;
"04") icon="󱑎" ;;
"05") icon="󱑏" ;;
"06") icon="󱑐" ;;
"07") icon="󱑑" ;;
"08") icon="󱑒" ;;
"09") icon="󱑓" ;;
"10") icon="󱑔" ;;
"11") icon="󱑕" ;;
esac

printf " %s %s \n" "$icon" "$(date '+%I:%M')"
