#!/bin/sh

api="https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum&vs_currencies=idr"

data=$(curl -s "$api")
btc=$(echo "$data" | sed -n 's/.*"bitcoin":{"idr":\([^}]*\)}.*/\1/p')
eth=$(echo "$data" | sed -n 's/.*"ethereum":{"idr":\([^}]*\)}.*/\1/p')

format_rupiah() {
  echo "$1" | rev | sed 's/...\B/&./g' | rev
}

btc_formatted=$(format_rupiah "$btc")
eth_formatted=$(format_rupiah "$eth")

btc_icon="󰆬"
eth_icon="󰡪"

printf " %s Rp%s  %s Rp%s \n" "$btc_icon" "$btc_formatted" "$eth_icon" "$eth_formatted"
