#!/bin/sh

read total used <<< $(free -m | awk '/^Mem/ { print $2, $3 }')

used_gb=$(awk "BEGIN { printf \"%.2f\", $used/1024 }")
total_gb=$(awk "BEGIN { printf \"%.2f\", $total/1024 }")

printf " 󰍛 %s/%s GiB \n" "$used_gb" "$total_gb"
