#!/bin/sh

vol=$(amixer get Master | grep -o '[0-9]\+%' | head -n1 | tr -d '%')
mute=$(amixer get Master | grep -o '\[off\]')

if [ "$mute" = "[off]" ]; then
  icon=""
  printf " %s MUTE \n" "$icon"
else
  if [ "$vol" -eq 0 ]; then
    icon=""
  elif [ "$vol" -le 30 ]; then
    icon=""
  else
    icon=""
  fi
  printf " %s %s%% \n" "$icon" "$vol"
fi
