#!/bin/sh

color_normal="#000000"
color_mute="#FF0000"

get_volume_info() {
  vol=$(amixer get Master | grep -o '[0-9]\+%' | head -n1 | tr -d '%')
  mute=$(amixer get Master | grep '\[on\]' >/dev/null && echo 0 || echo 1)
  echo "$vol $mute"
}

read speaker_vol speaker_mute < <(get_volume_info)

if [ "$speaker_mute" -eq 1 ]; then
  printf "^c%s^  Mute\n" "$color_mute"
else
  if [ "$speaker_vol" -eq 0 ]; then
    icon=""
  elif [ "$speaker_vol" -le 30 ]; then
    icon=""
  else
    icon=""
  fi
  printf "^c%s^ %s %s%% \n" "$color_normal" "$icon" "$speaker_vol"
fi
